### ISSUE TITLE
Xlating FIR Filter NCO does not match the Signal Source implementation

### ISSUE THREAD

**Issue by jmfriedt** [gnuradio/gnuradio#7208] opened 2024-03-22 15:02 UTC
### What happened?

The following flowchart illustrates how the Xlating FIR NCO local oscillator phase is drifting with respect to the Signal Source. Low-pass filtering the Signal Source output does not impact phase over time (the FIR is not drifting) but the Xlating FIR, whether low-pass filtered or not, is drifting. This drift is frequency proportional, but should not occur (we are computing exp(jwt)xexp(-jwt)=1 so the phase output should be constant).

### System Information

OS: Debian GNU/Linux SID
GR Installation Method: apt install gnuradio-dev
Source: deb http://ftp.fr.debian.org/debian/ sid main contrib non-free

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

See attached:
![phastest](https://github.com/gnuradio/gnuradio/assets/10595447/518c8f5d-84c2-4493-8330-601ee5881d97)

**Comment by willcode** [comment] 2024-03-22 15:53
Is this related to #6800?

**Comment by argilo** [comment] 2024-10-01 19:15
> Is this related to https://github.com/gnuradio/gnuradio/issues/6800?

Yes, I believe the root cause is the same. So I'll close this in favour of #6800.

**Closed by argilo** 2024-10-01 19:15 UTC
