### ISSUE TITLE
font color

### ISSUE THREAD

**Issue by Taxom** [gnuradio/gnuradio#6389] opened 2022-11-19 04:02 UTC
### What happened?

I have a problem with with font color in the configuration of graphs. White font on a white background. 
![изображение](https://user-images.githubusercontent.com/20313019/202833222-f554b24b-2676-4123-b6a4-24825e9b0a60.png)

### System Information

System:    Kernel: 5.10.0-19-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 
           Desktop: Cinnamon 5.4.12 tk: GTK 3.24.24 wm: Mutter dm: LightDM Distro: LMDE 5 Elsie 
           base: Debian 11.2 bullseye 
GNU Radio Companion 3.8.2.0 (Python 3.9.2)

### GNU Radio Version

3.8  (maint-3.8)

### Specific Version

3.8.2.0

### Steps to Reproduce the Problem

start app 
open graph configuration

**Comment by willcode** [comment] 2022-11-19 12:36
Duplicate of https://github.com/gnuradio/gnuradio/issues/2374
This was fixed in #4551 (v3.10) and #4690 (v3.9).
v3.8 is no longer actively maintained, but you may be able to apply the diffs in these fixes to your own system.

**Closed by willcode** 2022-11-19 12:36 UTC
