### ISSUE TITLE
dev-4.0: invalid cast when calling getter an enum parameter

### ISSUE THREAD

**Issue by frankosterfeld** [gnuradio/gnuradio#6453] opened 2023-01-04 13:13 UTC
### What happened?

seen with dev-4.0 (commit 47959775)

I have an enum parameter defined like this:

```
-   id: mode
    label: Sink Mode
    dtype: enums/freq_sink_mode_t
    is_enum: true
    gettable: true
```

The generated getter looks like this:

```
freq_sink_mode_t freq_sink::mode()
{
    return pmtv::cast<freq_sink_mode_t>(request_parameter_query(params::id_mode));
}
```

Calling this method leads to  an exception `Invalid PMT Cast N2gr10digitizers16freq_sink_mode_tE...`

I guess this needs a pmtv::cast<int> which is then cast to freq_sink_mode_t.

### System Information

OS: (Linux Distro, Mac, Windows)
GR Installation Method: (native distro packages - apt, rpm, etc., Conda, Source

### GNU Radio Version

4.0-git (dev-4.0)

### Specific Version

dev-4.0 branch (commit https://github.com/gnuradio/gnuradio/commit/47959775a2f98674a2839e78bd5b7bce74ba4fe2)

### Steps to Reproduce the Problem

Add gettable enum-type parameter and call the getter.

**Comment by mormj** [comment] 2023-01-05 22:31
Thank you for sharing the issue - looks like you have done a ton of migration over to 4.0 - would love to hear more of your experience and feedback.

I couldn't reproduce locally the issue you were seeing:
https://github.com/mormj/gr4-test_enums

Had to add the `include:` in the yml

NOTE: There were a few other missing includes in pmt library - this needs to be checked in as well for current dev-4.0 OOTs to work more seamlessly (or at all):
https://github.com/gnuradio/pmt/pull/77

**Comment by frankosterfeld** [comment] 2023-01-06 10:38
I've adapted the unit test to reproduce the issue: https://github.com/frankosterfeld/gr4-test_enums/commit/d4095f9e84ed6a3aa3554da12b3cd2b52ed367fd

Basically, when I call mode(), the exception is triggered.

**Comment by mormj** [comment] 2023-01-06 11:34
Ah I see now where that's causing an issue.  Fix incoming.

**Comment by mormj** [comment] 2023-01-09 18:54
Not sure why github isn't automatically closing issues, but PR is now merged

**Closed by mormj** 2023-01-09 18:54 UTC
