### ISSUE TITLE
PulseAudio test (poor performance)

### ISSUE THREAD

**Issue by Red-Owl** [gnuradio/gnuradio#1761] opened 2018-05-04 23:18 UTC
i have build from source, i have a problem by performance, i have create a very simple test 
pulseaudio out (mic) pulseaudio in (speaker): one two tree four fi...speaker one 4 second later
without any signal processing
this is very long time.
tnx for your help
https://pastebin.com/zvM6KF2P (flowchart)

**Comment by marcusmueller** [comment] 2018-05-14 12:52
Thanks for reporting this! Without knowing more, I'd say that I don't know where your `pulseaudio_pa_*` blocks come from – they're as far as I can track not part of "official" mainline GNU Radio.

Since the default Audio sink works with the pulseaudio servers offering a software ALSA device, I'm not sure my recommendations would be anything but "use the default audio sink". So, unless you help me understand, I'll have to close this as "invalid" (since we're not the authors of the `pulseaudio_pa` blocks). Note that such closing isn't permanent; if this turns out to be relevant, we'll happily reopen!

Note that generally, GNU Radio is a buffer-oriented architecture [link](https://gnuradio.org/blog/buffers), and that GNU Radio will generally ask a source to fill as much of its output buffer as possible. If your source does that, and that buffer amounts to multiple seconds worth of audio samples: that's expected behaviour, and the way to fix that would be to write the source in a way that doesn't try to fill all the buffer at once.

**Closed by marcusmueller** 2018-05-14 12:52 UTC
Labels: invalid
