### ISSUE TITLE
GR Filter Designer Crash - scipy has no attribute complex128

### ISSUE THREAD

**Issue by jwkunz** [gnuradio/gnuradio#7235] opened 2024-04-01 00:30 UTC
### What happened?

It appears somebody accidentally used scipy.complex128 instead of numpy.complex128 in the filter_design.py.
This could be due to an deprication in the scipy library, or just an honest mistake.

Doing a text replace of scipy.complex128 with np.complex128 inside the file gnuradio/filter/filter_design.py will temporarily fix the problem.

Using scipy 1.12.0  and gnuradio 3.10.9.2

### System Information

OS: Arch Linux
GR Installation Method: radioconda (I also published a bug report in that repo for those devs)

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.9.2

### Steps to Reproduce the Problem

Steps to reproduce:
1)  Launch the gr_filter_design binary.

2) [Press design in the GUI on the default settings]

3) Error message and no response in the GUI

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
           ~~~~~~~~~^^^^^^
KeyError: 'complex128'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/gnuradio/filter/filter_design.py", line 833, in design
    self.design_fir(ftype, fs, gain, winstr)
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/gnuradio/filter/filter_design.py", line 877, in design_fir
    self.draw_plots(taps, params)
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/gnuradio/filter/filter_design.py", line 2329, in draw_plots
    self.update_time_curves()
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/gnuradio/filter/filter_design.py", line 1064, in update_time_curves
    if(type(self.taps[0]) == scipy.complex128):
                             ^^^^^^^^^^^^^^^^
  File "/home/jwkunz/radioconda/lib/python3.11/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'complex128'
```

**Comment by willcode** [comment] 2024-04-01 09:14
Duplicate of #7227

**Closed** 2024-04-01 09:14 UTC
