### ISSUE TITLE
error on windows 10 doesn't open any file in gnu radio companion

### ISSUE THREAD

**Issue by Zupayruna96** [gnuradio/gnuradio#4119] opened 2021-01-19 06:12 UTC
Error message output is: (gnuradio-companion.py:3804): GLib-GIO-ERROR **: 01:10:50.458: Settings schema 'org.gtk.Settings.FileChooser' is not installed

**Comment by gnieboer** [comment] 2021-01-19 17:07
This is likely a windows-specific error, which installer are you using?

**Comment by gnieboer** [comment] 2021-01-19 17:41
Disregard, duplicated in most recent installer!

**Comment by gnieboer** [comment] 2021-01-19 18:02
The issue is multiple schemas were merged into share/glib-2.0/schemas/, with each pre-compiled, but when combined only one compiled file is left.  So the schemas need to recompiled after combining.

**Comment by gnieboer** [comment] 2021-01-19 19:48
Please downloaded an updated installer (same link) and remove/reinstall.  Apologies, in my limited test setup the flowgraphs I use to test the install are already open so I didn't try to open dialog.

**Closed by gnieboer** 2021-01-19 19:48 UTC
Labels: Windows
