### ISSUE TITLE
`qa_hier_block2` fails intermittently

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/gnuradio#1154] opened 2017-01-05 17:12 UTC
The `qa_hier_block2` test failed for me on a fresh build of `maint` (`588fe5e99`), but I can't get it to fail again.

![hier_block2_fail](https://cloud.githubusercontent.com/assets/569571/21689906/1e6d3d36-d340-11e6-9b56-9accb10496ec.png)

I haven't yet tried debugging this, so I don't have much to offer in the way of additional details at this point.

**Comment by bastibl** [comment] 2017-01-05 22:34
Occasionally, I see random unit tests fail due to something thrift related. Did you have control port and thrift enabled?

**Comment by marcusmueller** [comment] 2020-10-30 13:38
doesn't fail in current CI (or locally for me), so closing as non-reproducible. Thrift is still borked.

**Closed by marcusmueller** 2020-10-30 13:38 UTC
Labels: Bug, Runtime
