### ISSUE TITLE
float_to_char: broken conversion in VOLK leads to spurious 0 in output

### ISSUE THREAD

**Issue by marcusmueller** [gnuradio/gnuradio#2022] opened 2018-09-20 17:29 UTC
![char_bug](https://user-images.githubusercontent.com/958972/45835654-f86cc280-bd0a-11e8-984f-7bc64c0031d2.png)

When using a sine source, and converting the output to char (and back to float for displaying reasons), we get a spurious 0 once in a while:

![demonstrate_f32_int8_problem grc](https://user-images.githubusercontent.com/958972/45835687-0e7a8300-bd0b-11e8-806e-361a9d782572.png)

Version 3.7.13.4 

https://github.com/gnuradio/gnuradio/blob/master/gr-blocks/lib/float_to_char_impl.cc#L58

calls VOLK's `volk_32f_s32f_convert_8i(out, in, d_scale, d_vlen*noutput_items)`.

So, we have a critical bug in VOLK.

**Comment by noc0lour** [comment] 2018-09-20 20:43
That's not a bug in VOLK. It's the rounding done by the `_mm_cvtps_epi32` call which is not truncating but actually rounding to the nearest integer. Being on a floating point edge `0.5` with some inaccuracy you can either land at 0 or -1 depending on the inaccuracy. Can you please paste the output of the sine wave? I've fired up gnuradio/volk#198 to fix the off-by-one bug in the conversion (which might accidentally fix your particular issue here).

**Comment by noc0lour** [comment] 2019-03-08 14:23
Fixed in newest volk

**Closed by noc0lour** 2019-03-08 14:23 UTC
Labels: Bug, blocks
