### ISSUE TITLE
ENABLE_STATIC_LIBS cmake flag no longer works

### ISSUE THREAD

**Issue by rfenlon** [gnuradio/gnuradio#7197] opened 2024-03-15 13:49 UTC
### What happened?

cmake does not recognize the ENABLE_STATIC_LIBS flag anymore so build does not produce static libraries as referenced in the [build documentation ](https://www.gnuradio.org/doc/doxygen/build_guide.html). 

It appears support for this was removed with commit ab2fb35677e38a384df3f9503d1f45f64bbc0374

### System Information

OS: ubuntu:focal
GR Installation Method: source

### GNU Radio Version

3.10 (maint-3.10)

### Steps to Reproduce the Problem

mkdir build
cd build
cmake -DENABLE_STATIC_LIBS=True ..

### Relevant log output

```shell
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_STATIC_LIBS
```

**Comment by willcode** [comment] 2024-03-15 13:55
Duplicate of #4452

**Closed by willcode** 2024-03-15 13:55 UTC
