### ISSUE TITLE
zeromq deprecation warnings

### ISSUE THREAD

**Issue by japm48** [gnuradio/gnuradio#5538] opened 2022-01-28 23:50 UTC
### What happened?

Building with zeromq support outputs a bunch of deprecation warnings.

Here is the log: https://gist.github.com/japm48/54b13a944fabb4838e21ccb7e8247b86

Of course, this is just a nuisance while compiling, but will likely become an error in the future.

If I find some spare time I'll submit a patch, including proper backwards compat.

### System Information

OS: Arch Linux
GR Installation Method: source
libzmq version: 4.3.4
cppzmq version: 4.8.0

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.10.0.0-22-g7712360d

### Steps to Reproduce the Problem

Compile gnuradio with zeromq support (`ENABLE_GR_ZEROMQ=ON`).

**Comment by willcode** [comment] 2022-01-29 01:28
Duplicate of https://github.com/gnuradio/gnuradio/issues/4728, closing this one.

**Closed by willcode** 2022-01-29 01:28 UTC
