### ISSUE TITLE
The master branch should have a recent tag.

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#4059] opened 2021-01-09 07:38 UTC
I would suggest commit https://github.com/gnuradio/gnuradio/commit/0901fcb5459c5169017c3073630d7aca158bd626 be tagged with v3.10.0.0git

**Comment by mbr0wn** [comment] 2021-02-15 16:47
Closing as dupe of #4161 .

**Closed by mbr0wn** 2021-02-15 16:47 UTC
Labels: master
