### ISSUE TITLE
import digital_swig error

### ISSUE THREAD

**Issue by V18006** [gnuradio/gnuradio#2464] opened 2019-04-22 11:20 UTC
Sir,
I am new to GNU radio, so sorry if this error is very basic !!  
I am getting an error while trying one of your codes given in 
[https://github.com/gnuradio/gnuradio/blob/master/gr-digital/python/digital/ofdm_txrx.py](url)
The error was: 
Traceback (most recent call last):
    File "ofdm_txrx.py", line 33, in <module>
      import digital_swig as digital
ImportError: No module named digital_swig
Sir, I used  "python ofdm_txrx.py" to run the code from the terminal.
Should I use any other way to run the code?

**Comment by marcusmueller** [comment] 2019-04-22 13:00
We're not just one sir, there's quite a few ladies here, too! Anyway, what you're describing sounds like an installation problem, not a GNU Radio bug, so I'm closing this issue.

**Comment by V18006** [comment] 2019-04-22 13:13
Sir / Madam,
But all the other blocks are working. What should I do?

**Comment by michaelld** [comment] 2019-04-22 13:45
OK so -some- of GNU Radio is installed properly. When you installed GNU Radio, did you make a note of which components were enabled / disabled? If not, go back and revisit the CMake output, maybe gr-digital was not enabled for some reason?

**Comment by michaelld** [comment] 2019-04-27 11:40
No response for 5 days. I'm closing this issue. If the issue is still relevant for the original poster, please reopen and post more information here to help us diagnose the issue.

**Closed by michaelld** 2019-04-27 11:40 UTC
Labels: invalid
