### ISSUE TITLE
QT GUI Sink display anomaly

### ISSUE THREAD

**Issue by duggabe** [gnuradio/gnuradio#3865] opened 2020-10-19 17:38 UTC
When a QT GUI Sink is opened, the Frequency Display tab is selected, but the plot only occupies about 1/2 of the window width. As soon as the window is resized or another tab is selected, going back to the Frequency Display displays properly.

See ~/gnuradio/gr-qtgui/examples/gui_sink.grc

**Comment by drmpeg** [comment] 2020-10-19 20:21
Confirmed.

**Comment by dl1ksv** [comment] 2020-11-03 08:07
Works for me with the actual master branch

**Comment by duggabe** [comment] 2020-11-03 12:01
Ubuntu 20.04.1
GR/GRC 3.9.0.0-git built from source 26 Aug 2020
the first time you run it, if the window is very small, you might not see it. So make the window larger (maybe 1/2 screen), close that window, and then run it again. without touching it, the frequency plot will only occupy from the left side to underneath the 'Constellation Display' tab. then, resizing the window, or changing to another tab and going back will make the frequency plot full width.

**Comment by duggabe** [comment] 2020-11-03 13:02
![Screenshot from 2020-11-03 07-00-28](https://user-images.githubusercontent.com/47478634/97988343-72a11980-1da2-11eb-8bdf-cb0c3c518c47.png)

**Comment by dl1ksv** [comment] 2020-11-11 09:54
Took some time to find the reason. But now it should be fixed in 3.9 by #3929

**Closed** 2020-11-26 13:16 UTC
Labels: QTGUI
