### ISSUE TITLE
Sending a message WHILE a flowgraph is closing.

### ISSUE THREAD

**Issue by reiinakano** [gnuradio/gnuradio#1735] opened 2018-04-17 10:52 UTC
While a flow graph is running, it's easy to have an external program get data from various blocks via messages through the ZMQ message sink. My question is what if the message is generated AFTER a flow graph is closed e.g. a png image of the full waterfall plot?

When I send a message to the ZMQ message sink from the `stop` function of a block, it doesn't work since it seems that at that point, the ZMQ message sink no longer accepts/processes messages. Is there a way to keep a block from closing until all other blocks that send messages to it have closed? Is the `stop` function the correct place to put logic like this (sending out a final message after ending a flowgraph)?

Also, does calling `stop` on the flow graph "gracefully" stop the flowgraph i.e. scheduler stops source blocks then lets the downstream blocks work until there is no data left in the buffers?

**Comment by willcode** [comment] 2018-05-05 14:26
No, stop() is not coordinated. Everything just stops via thread interrupts. Most blocks don't do anything on stop().

**Comment by willcode** [comment] 2020-10-28 13:04
This may be addressed by https://github.com/gnuradio/gnuradio/pull/3866, and is similar to https://github.com/gnuradio/gnuradio/issues/3872. @reiinakano can this be closed?

**Comment by marcusmueller** [comment] 2023-12-21 01:25
this is a support request, not a bug report, I'm afraid, and we're currently cleaning up the issue tracker

**Closed by marcusmueller** 2023-12-21 01:25 UTC
Labels: invalid
