### ISSUE TITLE
QA: qa_packet_format timeout

### ISSUE THREAD

**Issue by noc0lour** [gnuradio/gnuradio#2216] opened 2018-12-05 16:20 UTC
From: https://ci.gnuradio.org/buildbot/#/builders/51/builds/331/steps/5/logs/stdio

```
333/360 Test #333: qa_packet_format ...................................***Timeout 120.10 sec
```

**Comment by argilo** [comment] 2022-05-12 03:41
I recently spent some time analyzing and fixing CI failures, and I didn't observe this issue. Looking at the tests themselves, I see they involve message passing and suspect that any past timeouts may have been caused by the race condition that was fixed in https://github.com/gnuradio/gnuradio/pull/5754.

Since this test is most likely no longer flaky, I'll close off this issue.

**Closed by argilo** 2022-05-12 03:41 UTC
Labels: QA
