### ISSUE TITLE
HELP with $ pybombs install gnuradio

### ISSUE THREAD

**Issue by sabakali** [gnuradio/gnuradio#1808] opened 2018-06-04 11:24 UTC
Hello !
I have Linux Ubuntu 16.04 LTS. I am trying to install GNURadio by using PyBombs.
After I executed this command : $ pybombs install gnuradio

I got this final output : 
PyBOMBS.install_manager - INFO - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.install_manager - INFO - Installing package: autotools-bootstrap
PyBOMBS.Packager.source - WARNING - Cannot find a source URI for package autotools-bootstrap
PyBOMBS.install_manager - ERROR - Error installing package autotools-bootstrap. Aborting.

And there were some errors in red when it was processing the install command.

Any help will be highly appreciated.

Thank you!

**Comment by y-iskw** [comment] 2018-06-08 03:46
As you may know, the building procedure using pybombs is described in GitHub.
How about this?

$ rm -rf .pybombs 
$ rm -rf ~/prefix

$ pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
$ pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
$ mkdir prefix
$ pybombs prefix init ~/prefix/default/
$ pybombs fetch gnuradio

I edited my CMakeLists.txt as follows for g++.
Simply SET(CMAKE_CXX_STANDARD 98)  to  SET(CMAKE_CXX_STANDARD 11) .

For example:  /home/YourUserName/prefix/default/src/gnuradio/CMakeLists.txt
(snip)
# Configure C++ standard if not externally specified (will actually be              
# set after CppUnit check below). Use the variable CMAKE_CXX_STANDARD 
# since it will actually be used for this purposes starting in CMake 3.1.    
IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    SET(CMAKE_CXX_STANDARD 11)      
ELSEIF(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    SET(CMAKE_CXX_STANDARD 98)
ELSEIF(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    SET(CMAKE_CXX_STANDARD 98)
ELSE()
    message(warning "C++ standard could not be set because compiler is not GNU, Clang or MSVC.")
ENDIF()
(snip)

$ pybombs install gnuradio

then I got  "PyBOMBS.install_manager - INFO - Installation successful".
I am afraid that this is not a very good procedure, but it is possible to build a GNU radio.

**Comment by dkozel** [comment] 2018-06-08 13:50
@y-iskw There was a bug in GNU Radio's master branch that was fixed yesterday. Changing the CMAKE_CXX_STANDARD is not needed now.

@sabakali Unfortunately we'll need more of the output to see what the install issues are. Can you please rerun pybombs with `-v` to make the output more verbose?

**Comment by dkozel** [comment] 2018-06-17 16:15
@sabakali Can you please let us know if you've solved the issue? If not, can you please run `pybombs --version` and let us know the results as well as post the log of running pybombs with `-v`?

**Comment by mbr0wn** [comment] 2018-07-12 03:59
This looks more like a support request and not a bug report -- closing now.

**Closed by mbr0wn** 2018-07-12 03:59 UTC
Labels: clarification needed

**Comment by lovingQi** [comment] 2018-07-19 14:32
Hello !
after I run pybombs install gnuradio
display
`$ pybombs install gnuradio
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.install_manager - INFO - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.install_manager - ERROR - Package has no install method: autotools-bootstrap
`
there are some errors saying that no install method:autools-bootstrap

how to solve it?
after I run pybombs --version
display 
`$ pybombs --version
2.3.2
`
when I run pybombs -v
display
`$ pybombs -v
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /etc/pybombs\conf                                                                                                                ig.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: H:\cygwin64\home\                                                                                                                worker\.pybombs\config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: ordereddict([('default_prefix'                                                                                                                , 'C:\\gnu')])
PyBOMBS.ConfigManager - DEBUG - Template directory: c:\python27\lib\site-package                                                                                                                s\pybombs\templates
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /etc/pybombs\                                                                                                                config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: H:\cygwin64\h                                                                                                                ome\worker\.pybombs\config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Using default_prefix as prefix (C:\gn                                                                                                                u)
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Choosing default prefix config dir: C                                                                                                                :\gnu\.pybombs
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: C:\gnu\.pybom                                                                                                                bs\config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix source dir is: C:\gnu\src
PyBOMBS.Inventory - DEBUG - Trying to load inventory file C:\gnu\.pybombs\invent                                                                                                                ory.yml...
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix-local recipe dir is: C:\gnu\.p                                                                                                                ybombs\recipes
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: C:\gnu\.pybombs\c                                                                                                                onfig.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Full list of recipe locations: ['C:\\gnu\\.pybom                                                                                                                bs\\recipes', 'H:\\cygwin64\\home\\worker\\.pybombs\\recipes\\gr-recipes', 'H:\\                                                                                                                cygwin64\\home\\worker\\.pybombs\\recipes\\gr-etcetera', 'c:\\python27\\lib\\sit                                                                                                                e-packages\\pybombs\\recipes']
PyBOMBS.ConfigManager - DEBUG - Named recipe locations: {'gr-etcetera': 'git+htt                                                                                                                ps://github.com/gnuradio/gr-etcetera.git', 'gr-recipes': 'git+https://github.com                                                                                                                /gnuradio/gr-recipes.git'}
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: C:\gnu\.pybombs\reci                                                                                                                pes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory 'C:\gnu\.pybombs\recipes'                                                                                                                 for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 0 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: H:\cygwin64\home\wor                                                                                                                ker\.pybombs\recipes\gr-recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory 'H:\cygwin64\home\worker\                                                                                                                .pybombs\recipes\gr-recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 190 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: H:\cygwin64\home\wor                                                                                                                ker\.pybombs\recipes\gr-etcetera
PyBOMBS.RecipeListManager - DEBUG - Scanning directory 'H:\cygwin64\home\worker\                                                                                                                .pybombs\recipes\gr-etcetera' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 99 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: c:\python27\lib\site                                                                                                                -packages\pybombs\recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory 'c:\python27\lib\site-pac                                                                                                                kages\pybombs\recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 11 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
usage: pybombs [-h] [--version] [-p PREFIX] [--prefix-conf PREFIX_CONF]
               [--config CONFIG] [--config-file CONFIG_FILE] [-r RECIPES] [-q]
               [-v] [-y]
               <command> ...
pybombs: error: too few arguments
`
The computer's operating system is win10 64-bit and I use cygwin to run
Thank you!

**Comment by MGasztold** [comment] 2018-09-09 21:34
I have the same issue as above:

```Package has no install method: autotools-bootstrap```
