### ISSUE TITLE
Companion is unresponsive after launch

### ISSUE THREAD

**Issue by Kllngii** [gnuradio/gnuradio#5613] opened 2022-02-27 00:41 UTC
I am using a recent M1 Macbook with up to date firmware (macOS 12.2.1) and installed gnuradio via homebrew `brew install gnuradio`. After starting the companion using `gnuradio-companion&` I noticed some strange black blocks or sometimes a completly black window. However, it is still partly responsive, I am still able to double click blocks to open their properties and to open the save and load dialogs. The block selector on the righthand side and keyboard shortcuts are not working.

The strange thing is, that everything works fine until I save a file for the first time. If I later delete the saved .grc file everything is back to normal (except for small black boxes shown in the second picture)

<img width="1159" alt="Bildschirmfoto 2022-02-27 um 01 29 29" src="https://user-images.githubusercontent.com/34012522/155863397-4856b23c-5c60-4f4f-8951-71c0b84223f8.png">
<img width="1164" alt="Bildschirmfoto 2022-02-27 um 01 31 07" src="https://user-images.githubusercontent.com/34012522/155863480-75b8483d-d533-40a2-88db-c9fe8b3ad743.png">

**Comment by kaiser-ren** [comment] 2022-03-04 14:15
I have the same issue, I think the unusual behavior was started while I tried to connect the different components. 
My machine is MacBook Pro M1, python is 3.9.10, gnuradio is 3.9.3.0. 

I also noticed that below warning was appeared in the terminal, I below my machine has matplotlib. 

_Slow YAML loading (libyaml not available)
<<< Welcome to GNU Radio Companion 3.9.3.0 >>>

Block paths:
	/opt/homebrew/share/gnuradio/grc/blocks
gr::log 2022-03-04 22:14:11,081 :WARN: Matplotlib is a required dependency to use DistanceRadar and AzElPlot.  Please install matplotlib to use these blocks (https://matplotlib.org/)_

**Comment by Kllngii** [comment] 2022-03-04 15:11
I also got that slow YAML loading warning even though I‘ve installed libyaml with `brew install libyaml`.

**Comment by kaiser-ren** [comment] 2022-03-05 11:53
Provide more clues on this issue.  
I have another MacBook, it's not Apple Silicon, old one. I had installed gnuradion before and updated it to 3.9.3.0 this week. This MacBook had the same issue I described in the previous reply. 
However, after:
brew uninstall gnuradio
brew cleanup gruradio
brew install gnuradio

Gnuradio works fine on this old fashion MacBook. I will try this on my Apple Silicon MacBook. This is the screenshot when everything works well. 
![Uploading Screen Shot 2022-03-05 at 7.46.05 PM.png…]()

**Comment by kaiser-ren** [comment] 2022-03-05 12:14
> Provide more clues on this issue. I have another MacBook, it's not Apple Silicon, old one. I had installed gnuradion before and updated it to 3.9.3.0 this week. This MacBook had the same issue I described in the previous reply. However, after: brew uninstall gnuradio brew cleanup gruradio brew install gnuradio
> 
> Gnuradio works fine on this old fashion MacBook. I will try this on my Apple Silicon MacBook. This is the screenshot when everything works well.
> 
> <img alt="Screen Shot 2022-03-05 at 7 46 05 PM" width="1277" src="https://user-images.githubusercontent.com/4544551/156881871-ab4e3d4f-0292-4a06-a7c6-a9388a1f30ca.png">

I just tried above three commands on MacBook (Apple Silicon), this method doesn't work and the issue is still the same like @Kllngii mentioned before.

**Comment by kaiser-ren** [comment] 2022-03-07 09:16
I also tried sudo port install gnuradio, the installation was successful, however, while I tried to launch gnuradio, the application didn't even pop-up.

**Comment by wlopez-enkoding** [comment] 2022-03-23 00:43
It’s weird because I don’t have a M1 chip but I have the same problem 🤔

**Comment by kaiser-ren** [comment] 2022-03-23 04:51
> It’s weird because I don’t have a M1 chip but I have the same problem 🤔

Sound like a common issue, I hope certain expert can give a workaround for this issue, or a timeline to fix. 
Appreciated in advance.

**Comment by wlopez-enkoding** [comment] 2022-04-01 00:14
Hey guys I came to tell you that in my case it was a problem that in the last versión in master branch was fixed. In short (for now) I had to turn scaling off in my Mac and that fixed the problem, @Kllngii maybe you should check out this option 🤷🏻‍♂️ C Ya !

**Comment by justacec** [comment] 2022-04-01 19:01
@wlopez-enkoding Do you mean the "main" branch or the "master" branch (for clarification).  Also, how did you disable the scaling?

**Comment by wlopez-enkoding** [comment] 2022-04-03 01:16
> @wlopez-enkoding Do you mean the "main" branch or the "master" branch (for clarification). Also, how did you disable the scaling?
> 
> edit: found that possibly setting "QT_AUTO_SCREEN_SCALE_FACTOR"=1 in the env might do the trick

yeah main branch. You can disable scaling in system preferences.

<img width="658" alt="Screen Shot 2022-04-02 at 22 16 30" src="https://user-images.githubusercontent.com/9939892/161407077-169d8dfb-15c4-46d7-b621-fa0a20b90cd1.png">

**Comment by justacec** [comment] 2022-04-03 08:08
But that would disable scaling for everything right.  The env bar seems to do it just for the app.

**Comment by wlopez-enkoding** [comment] 2022-04-03 13:34
> But that would disable scaling for everything right. The env bar seems to do it just for the app.
> […](#)

env didn't work for me 😕

**Comment by ryanvolz** [comment] 2022-04-05 19:29
> Hey guys I came to tell you that in my case it was a problem that in the last versión in master branch was fixed. In short (for now) I had to turn scaling off in my Mac and that fixed the problem, @Kllngii maybe you should check out this option 🤷🏻‍♂️ C Ya !

Let me see if I have this right. What I'm reading sounds like another manifestation of the bug that was fixed with https://github.com/gnuradio/gnuradio/pull/5111. Are all of these statements correct?:

1. Everyone experiencing this issue is using GNU Radio 3.9.3 or earlier on a machine with a "Retina" display (high DPI).
2. The problem goes away if you disable resolution scaling for the display.
3. The problem also goes away if you use GNU Radio built from the main branch (or really 3.9.4 or later, because it includes the fix linked above).

For everyone still having this problem and are stuck with GR 3.9.3, try making this change in the installed python code: https://github.com/gnuradio/gnuradio/pull/4814#issuecomment-925190019.

**Comment by justacec** [comment] 2022-04-05 21:34
Hate to break it.   I had the issue after building from the main branch the other day.  I set the env var to disable the scaling, seems like it worked.

**Comment by ryanvolz** [comment] 2022-04-06 00:34
> Hate to break it. I had the issue after building from the main branch the other day. I set the env var to disable the scaling, seems like it worked.

Interesting. You set `QT_AUTO_SCREEN_SCALE_FACTOR=1` in the environment, and not the global scaling factor, and that fixed it? GRC is gtk-based, so the QT environment variable shouldn't have any effect as far as I can tell, but the global setting would.

**Comment by wlopez-enkoding** [comment] 2022-04-07 01:30
> > Hey guys I came to tell you that in my case it was a problem that in the last versión in master branch was fixed. In short (for now) I had to turn scaling off in my Mac and that fixed the problem, @Kllngii maybe you should check out this option 🤷🏻‍♂️ C Ya !
> 
> Let me see if I have this right. What I'm reading sounds like another manifestation of the bug that was fixed with #5111. Are all of these statements correct?:
> 
> 1. Everyone experiencing this issue is using GNU Radio 3.9.3 or earlier on a machine with a "Retina" display (high DPI).
> 2. The problem goes away if you disable resolution scaling for the display.
> 3. The problem also goes away if you use GNU Radio built from the main branch (or really 3.9.4 or later, because it includes the fix linked above).
> 
> For everyone still having this problem and are stuck with GR 3.9.3, try making this change in the installed python code: [#4814 (comment)](https://github.com/gnuradio/gnuradio/pull/4814#issuecomment-925190019).

You're right, this is my workaround due to my brew installation.

**Comment by wlopez-enkoding** [comment] 2022-04-07 01:31
> > Hate to break it. I had the issue after building from the main branch the other day. I set the env var to disable the scaling, seems like it worked.
> 
> Interesting. You set `QT_AUTO_SCREEN_SCALE_FACTOR=1` in the environment, and not the global scaling factor, and that fixed it? GRC is gtk-based, so the QT environment variable shouldn't have any effect as far as I can tell, but the global setting would.

What didn't work for me was setting a OS Global Environment Variable, I was wrong ?

**Comment by ryanvolz** [comment] 2022-11-10 20:17
I'm unclear if people here are still having problems, but: any chance https://github.com/gnuradio/gnuradio/pull/6352 fixes this? That's a python-only fix, so you can manually edit the appropriate installed python files to test it.

**Comment by marcusmueller** [comment] 2024-01-31 22:56
since we haven't heard from this in a year after asking whether the problem persists: closing

**Closed by marcusmueller** 2024-01-31 22:56 UTC
Labels: Mac OS X, Triage::needed
