### ISSUE TITLE
File Sink fails on Windows when no path is specified or there are special characters

### ISSUE THREAD

**Issue by SantaTitular** [gnuradio/gnuradio#5101] opened 2021-09-26 16:01 UTC
Hello, 

I just installed GNURadio 3.8 x64 on my Windows 10 Pro-based PC. 

I have the following flowgraph where I implement a simple binary signal generator.

![image](https://user-images.githubusercontent.com/68435474/134815186-3826907a-74cd-4686-be2c-4d5f58c1554d.png)

Yet, when I run, I can't seem to save the bytes using the File Sink block

![image](https://user-images.githubusercontent.com/68435474/134815237-79fe7711-8f38-4aad-ac31-3bad27848476.png)

I tried giving the full access to Gnu Radio 3.8 folders and still can't work around the problem. Anyone can help?

Thanks in advance for the help!

**Comment by dkozel** [comment] 2021-09-26 16:39
Hi @SantaTitular  Two ideas:

Try using a full file path in the File Sink, so `C:\Users\tomas\out_1.dat` for instance.

Two, I see you have some spaces in the current file path and also a symbol in `1 semestre`. Possibly in 3.8 that is not supported. Can you try a folder without spaces and without any special characters?

I recommend joining the [GNU Radio Chat](https://app.element.io/#/room/#gnuradio:gnuradio.org) where folks can help more interactively.

**Comment by SantaTitular** [comment] 2021-09-27 10:02
Hi @dkozel thank you so much for the quick reply. I tested it and indeed your first suggestion worked! By inputting C:\Users\tomas\out_1.dat and C:\Users\tomas\out_2.dat I was able to create/overwrite the files with the bytes.

Regarding your second sugestion, I tested changed the directory of the script towards C:\Users\tomas and just having out1.dat and out2.dat, and still gave me a permission error. Maybe it is a bug?

Thanks, I'll be joining the GNU Radio chat at once!

**Comment by dkozel** [comment] 2021-09-27 13:06
I'm glad that worked. Yes, this sounds like a bad behavior in the block or environment. Would you be willing to do two additional checks to try to narrow down the issues?

1) A path with a space. ie `C:\Users\tomas\test folder\out_1.dat`
2) A path with a special character. ie `C:\Users\tomas\1°Semestre\out_1.dat`

Can you also say where you got the Windows installer and the exact version of GNU Radio. You can find that in GRC under the help menu.

Thanks!

**Comment by SantaTitular** [comment] 2021-09-27 14:34
Hi again @dkozel ,

I tested both of your suggestions and seems that, with the second test, i.e., a path with the special character, a directory error occurred whereas the first test, with a space, caused no issue. It seems that the special character introduced faulty characters in the path (image below)

![image](https://user-images.githubusercontent.com/68435474/134928254-e03e47e5-8480-40cd-b6f0-ec9e206053d0.png)


I downloaded the windows installer from here: [http://www.gcndevelopment.com/gnuradio/index.htm](http://www.gcndevelopment.com/gnuradio/index.htm) and the exact version is: GR 3.8.2.0 py3.9 

![image](https://user-images.githubusercontent.com/68435474/134928378-1f58b882-ddd2-4d6d-9750-168dc2255b83.png)

In sum, it appears that the permission errors occurs when I do not have a specific path for the file (which is solved by placing the path) and path with special characters lead to errors in the path when executing (so no special characters)

**Comment by dkozel** [comment] 2021-09-27 15:44
Perfect, thank you. Possibly 3.9 is better, but this gives us a lot of information about the issue.

**Comment by dkozel** [comment] 2021-09-29 09:06
Duplicate of https://github.com/gnuradio/gnuradio/issues/4323

**Closed by dkozel** 2021-09-29 09:06 UTC
Labels: Bug, Windows
