### ISSUE TITLE
feature-grc-qt Minor Issues

### ISSUE THREAD

**Issue by dkozel** [gnuradio/gnuradio#6957] opened 2023-11-15 11:41 UTC
This is a collection of minor issues or notes found while testing the new Qt version of GRC.

Last checked on 4e444b7ff

- [x] Properties menu does not open when using a block's right click menu
- [x] Opening a GRC file immediately modifies it so it cannot be closed without saving
- [x] Right clicking on an unselected block does not select it and give access to options like enable, disable, properties

**Comment by haakov** [comment] 2023-11-15 23:23
- [ ] Ctrl+Scroll zooms in on the top left corner. Maybe it should zoom in on where the mouse is?

**Comment by AsriFox** [comment] 2023-11-30 15:54
> * [ ] Running on Wayland: `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()`

@haakov Where exactly does this occur? I can't reproduce this in GNOME Wayland (Ubuntu 22.04LTS VM), Plasma Wayland (Ubuntu 23.10), Hyprland, cage or weston (Arch).

**Comment by AsriFox** [comment] 2023-12-04 19:24
I can reproduce the `qt.qpa.wayland` bug in weston (Arch), GNOME 42.9 (Ubuntu 22.04LTS VM) and GNOME 45.2 (Fedora 39 VM). However, I can't reproduce it in Hyprland, cage (Arch) or Plasma Wayland (Ubuntu 23.10). I can see the message in GNOME 45 (Ubuntu 23.10), but menus appear in correct locations.

**Comment by AsriFox** [comment] 2023-12-04 19:48
The problem with `add_block_from_query` looks like this:
![grc_tests_add_block_from_query](https://github.com/gnuradio/gnuradio/assets/91423563/5ae79926-a522-4613-8a31-12524735f193)
Here are the test logs from running `ctest -R grc_tests` with `QT_QPA_PLATFORM=wayland` and `QT_QPA_PLATFORM=xcb` on different systems:
[Arch_Hyprland_wayland_Test.log](https://github.com/gnuradio/gnuradio/files/13550657/Arch_Hyprland_wayland_Test.log)
[Arch_Hyprland_xcb_Test.log](https://github.com/gnuradio/gnuradio/files/13550658/Arch_Hyprland_xcb_Test.log)
[Fedora_Gnome45.2_wayland_Test.log](https://github.com/gnuradio/gnuradio/files/13550659/Fedora_Gnome45.2_wayland_Test.log)
[Fedora_Gnome45.2_xcb_Test.log](https://github.com/gnuradio/gnuradio/files/13550660/Fedora_Gnome45.2_xcb_Test.log)
[Ubuntu_Gnome42.9_wayland_Test.log](https://github.com/gnuradio/gnuradio/files/13550661/Ubuntu_Gnome42.9_wayland_Test.log)
[Ubuntu_Gnome42.9_xcb_Test.log](https://github.com/gnuradio/gnuradio/files/13550663/Ubuntu_Gnome42.9_xcb_Test.log)
[Ubuntu_Gnome45_xcb_Test.log](https://github.com/gnuradio/gnuradio/files/13550664/Ubuntu_Gnome45_xcb_Test.log)
[Ubuntu_Plasma_xcb_Test.log](https://github.com/gnuradio/gnuradio/files/13550665/Ubuntu_Plasma_xcb_Test.log)

**Comment by dkozel** [comment] 2024-02-06 22:59
Thanks for tackling many of the initially found minor issues. Here's another set I found while looking at the new features. Again, just notes so we don't forget them over time and anyone interested has a list to look at.

- [ ] Block comments only display as much text as fits exactly under the block's outline. Replicate by inserting a long comment.
- [ ] Block comments only display one line of text and block property is a single line field rather than multi line.
- [ ] Note block displays text incorrectly. Likely a due to one or both of the above items. Open mpsk_stage6.grc example.
- [ ] Blocks rotated 180 degrees are visually upside-down. Gtk GRC flips the block ports but not text in this case, easier to read.
- [ ] Connector arrows face in the wrong direction on input ports on a rotated block.
- [ ] Block property dialog fields all display "TYPE" rather than actual parameter type.
- [ ] Variable Editor window shows "<Open Properties>" for many variable values rather than a calculated value. For example a `QT GUI Range` block's variable.
- [ ] Connector curves don't render well when it's start and end are too close together.
- [ ] Align blocks feature not yet implemented.

**Comment by dkozel** [comment] 2024-02-10 11:23
- [ ] Python Block properties UI not implemented. Currently gives a raw text field for the code rather than an external editor.
- [ ] Virtual Sink ports do not change color based on connected port types
- [ ] Wildcard and Bus Connection ports are white and need an outline to be visible in a light theme

**Comment by haakov** [comment] 2024-02-10 20:46
>     * [ ]  Zooming in on the flowgraph canvas works using the `+` on the number pad but not on the main `+` key, need to add '=' as an alias, at least for US keyboard. in the Gtk codebase: [e50c3f8](https://github.com/gnuradio/gnuradio/commit/e50c3f80dd68c29f0f1331692dedefb95ab46ca7)

Should be fixed now for the Zoom in action. Is this just for zooming out, or is it for zooming out as well?

**Comment by lukazlim** [comment] 2024-03-07 04:12
I have a related issue to report for the feature-grc-qt branch too, last checked on https://github.com/gnuradio/gnuradio/commit/9f50457ddce76b1a30d94dfb6e29d6d5873fb436

- [ ] After removing the last-opened flowgraph, a FileNotFoundError error is returned when starting up with `gnuradio-companion --qt`
- [ ] After removing the last-opened flowgraph, a segfault occurs when starting up with `gnuradio-companion`

The `--gtk` version has no issues, it defaults to a new flowgraph which should be the intended behaviour.

![image](https://github.com/gnuradio/gnuradio/assets/111743620/f62ddfff-9799-4f9f-a678-d0f6b3cdacb1)

Restoring/moving the flowgraph back to its original directory will stop those errors until the program is closed while on a new unsaved flowgraph.

**Comment by haakov** [comment] 2024-03-24 03:59
>     * [ ]  After removing the last-opened flowgraph, a segfault occurs when starting up with `gnuradio-companion`

It looks like GRC Gtk is segfaulting, not GRC Qt. Can you confirm this? In that case, this should probably be a separate Github issue.

**Comment by marcusmueller** [comment] 2024-12-26 17:10
Hi. I admire the intent of keeping these things together in a list as "meta-issue", but we can't track progress on this, nor hint at any issues to interested outsiders, nor is it sensible to keep N different bug discussions alive.

Instead, I created a new issue for every outstanding `[ ]` in this list. Please refer to these issues.

Another remark: if we find ourselves in need of keeping track of progress across multiple issues, we can do that: github has "projects". I have, as an example, and as something well-tackleable in e.g. a hackfest, created the "[GRC-Qt feature parity](https://github.com/orgs/gnuradio/projects/10/views/2)" project.

I'll close this meta issue (this doesn't imply any of the issues mention within are closed), and would love for people to continue this excellent work by adding a quick, if wanted, completely formless issue, tag it "GRC-Qt" and whatever else is appropriate, and add it to the GRC-Qt project (we've had that for a long time!) and/or the aforementioned feature parity project. Thanks!

**Closed by marcusmueller** 2024-12-26 17:10 UTC
Labels: Bug, help wanted, GRC-Qt

**Comment by haakov** [comment] 2024-12-26 23:28
Good point. Thanks for dividing them up!
