### ISSUE TITLE
Issues in polar code module

### ISSUE THREAD

**Issue by dfdtc** [gnuradio/gnuradio#5430] opened 2021-12-29 09:36 UTC
After some test of polar code module (mainly using the polar_code_example.grc),I found some problem, maybe they are bugs or not.  
1. I can't set the channel type to AWGN, or it will give me a error:(only show a part of tracking message here)
```
File "/usr/lib/python3/dist-packages/gnuradio/fec/polar/channel_construction_awgn.py", line 197, in upper_convolve
    q[0, idx] = (tpm[0 / i] ** 2 + tpm[1, i] ** 2, 2)
ZeroDivisionError: division by zero
```
2. When I testing the encoder and decoder(SC and SCL)(using the original setting in the example(polar_code_example.grc)), I found that I can't decoding the message correctly, even the amplitude of noise have set to 0(meant no noise in transmitting). BUT, if I replace the encoding(and decoding) module from POLAR to LDPC, this example can give the correct output(by viewing the GUI output of Coded window).<br>
I'm not a researcher in this field, I just want to use the module to finish my own project. So.....sorry, I just know I have some problem. But I can't give a suggestion or some worked solutions for them.
Thank you for your notice of this issue.

**Comment by marcusmueller** [comment] 2021-12-29 13:19
Hi! Could you add the full error, and also maybe a picture / writedown of the exact parameters used? 

This does sound like a bug, so thanks for reporting!

**Comment by willcode** [comment] 2021-12-29 13:34
`upper_convolve()` in `channel_construction_awgn()` looks like it will always fail with a `/0` since `i in range(mu)`.

**Comment by dfdtc** [comment] 2021-12-30 05:19
(Working flow and parameters)
In conclusion:those flow are based on the example in "[/gnuradio/gr-fec/examples/polar_code_example.grc](https://github.com/gnuradio/gnuradio/blob/master/gr-fec/examples/polar_code_example.grc)". Only removed the part of uncoded signal displaying.
**Polar_code testing flow:**
![POLAR_flow](https://user-images.githubusercontent.com/6183346/147722817-a7627b09-f4b4-4986-9961-a4d2aebc1447.png)
**LDPC_code testing flow:**
![LDPC_flow](https://user-images.githubusercontent.com/6183346/147722793-07b2475b-802e-4026-814c-7347e8700547.png)
**Polar_code encoding and decoding(SC and SCL)(with noise)**
![POLAR_with_noise](https://user-images.githubusercontent.com/6183346/147722800-0cab181a-3906-4757-a7d3-f22e2a1cc80a.png)
**Polar_code encoding and decoding(SC and SCL)(WITHOUT noise)**
![POLAR_zero_noise](https://user-images.githubusercontent.com/6183346/147722801-099716a2-196d-4dec-a405-e62137e61cb7.png)
**LDPC encode and decode(with low amplitude of noise)**
![LDPC_low_noise](https://user-images.githubusercontent.com/6183346/147722797-5da453eb-c07b-4419-86fe-437688902f20.png)
![LDPC_low_noise2](https://user-images.githubusercontent.com/6183346/147722798-f81633ee-3ff7-4e02-8bfc-def27000d5c7.png)
**LDPC encode and decode(with high amplitude of noise)**
![LDPC_high_noise](https://user-images.githubusercontent.com/6183346/147722796-a69df6a4-e335-4b91-b699-349ac7b5c240.png)
_**The message in testing.txt (the "file source" block in working flow)is the repeating of text "testing"**_
**(Just in my point of view)**
As the picture showed, the polar_code module cannot decode the coding produced by polar_code_encoder(both SC and SCL), in both of noisy and noiseless environments. BUT, just replaced the encoder and decoder from POLAR to LDPC, this flow can give the right output(corrected message in low noise environment, partly corrected message in high noise environment).

**Comment by VladislavF** [comment] 2023-01-06 20:58
I can confirm the same issue occurs in GR 3.10.4

**Comment by VladislavF** [comment] 2023-01-06 21:02
> `upper_convolve()` in `channel_construction_awgn()` looks like it will always fail with a `/0` since `i in range(mu)`.

Is there any news on resolving this? Was this a syntax error or does it go deeper? I would offer my help, but I'm afraid I know absolutely nothing about polar codes, so I don't have any intuition here.

**Comment by willcode** [comment] 2023-01-06 21:53
There haven't been any changes to this file and `upper_convolve()` still looks really messed up. `tpm[0 / i]` is both useless and crashy. I don't know anything about polor codes either. @jdemel ?

**Comment by jdemel** [comment] 2023-01-07 11:19
A lot of papers on polar codes don't use this method for construction. Most resort to the Bhattacharyya Bounds method (the BEC channel option), or Gaussian Approximation. Also, Beta-Expansion is an interesting candidate that might produce the best results in the end.

The whole "channel" argument refers to the channel construction algorithm and its underlying assumption. You can use any and the results will mostly be the same. They vary be less than .1 dB and the preference for one algorithm over another may change if you choose a different polar decoder.
In retrospect it would've been better to call this argument "algorithm" and options would be: BB, GA, BE, DE.

The example flowgraph in its default configuration shouldn't break though.

**Closed** 2023-01-09 10:19 UTC
Labels: Bug, FEC
