### ISSUE TITLE
GRC: "Core" group in block list is often not clickable

### ISSUE THREAD

**Issue by nils-werner** [gnuradio/gnuradio#5843] opened 2022-05-11 08:49 UTC
### What happened?

When trying to collapse the "Core" group in the block list I am very frequently unable to do so. The triangular symbol is just not clickable, as the cursor switches from an arrow to a text-selection tool:

![not clickable](https://user-images.githubusercontent.com/88704/167809357-7ece8213-0f33-4be2-8aaa-131c0835765a.png)

Only in a very tiny space of just 1-2 pixels wide the cursor turns to an arrow and I can click the triangle:

![clickable](https://user-images.githubusercontent.com/88704/167809448-83da98a4-0a8e-4546-ad33-9df5a9e5a223.png)

### System Information

OS: Arch Linux, Gnome 3
GR Installation Method: Conda

### GNU Radio Version

3.10 (maint-3.10)

### Specific Version

3.10.1.1

### Steps to Reproduce the Problem

1. Launch GRC on a Linux machine with Gnome 3
2. Try to collapse "Core"

**Comment by marcusmueller** [comment] 2024-01-31 23:14
Interestingly, can't reproduce in a Gnome3 wayland x11 container. Hm. I don't really think it's a great idea to close this, but this is the criterion.

@nils-werner does the issue persist on your side? (By the way, have you tried the qt GRC branch? Might very much be to your liking :D )

**Closed** 2024-01-31 23:14 UTC
Labels: Bug, GRC
