### ISSUE TITLE
qwt_compat.h:No such file or directory

### ISSUE THREAD

**Issue by greyltc** [gnuradio/gnuradio#5316] opened 2021-11-11 18:47 UTC
https://github.com/gnuradio/gnuradio/blob/f9a693d7af02b6ce88fb0e4f3fad78390980c968/gr-qtgui/include/gnuradio/qtgui/DisplayPlot.h#L31

I think this comparison might be backwards.

**Comment by ryanvolz** [comment] 2021-11-12 14:46
Duplicate of #4956, which has been fixed by #5302 on the main branch and should be backported to maint-3.9 and maint-3.8 shortly.

**Closed by ryanvolz** 2021-11-12 14:46 UTC
