### ISSUE TITLE
gnuradio-3.8 pybombs build failes when dist 3.7.13.5 is installed

### ISSUE THREAD

**Issue by Phil67ago** [gnuradio/gnuradio#3402] opened 2020-04-23 12:07 UTC
Ref: https://www.mail-archive.com/discuss-gnuradio@gnu.org/msg70178.html

The order of swig's include path is wrong and dist's '/usr/include/gnuradio' is picked up.
This line is to late, see build-make-dump.txt
  -I/home/user/test/gnuradio/src/gnuradio/gr-blocks/lib/../include
[build-make-dump.txt](https://github.com/gnuradio/gnuradio/files/4522306/build-make-dump.txt)

Following patch is a ugly fix.
Some one with better knowledge need to take a closer look.
[gnuradio-cmake-swig-include.patch.txt](https://github.com/gnuradio/gnuradio/files/4522326/gnuradio-cmake-swig-include.patch.txt)

/Phil

**Comment by rear1019** [comment] 2020-04-27 15:04
Closing, duplicate of issue #3054.

@Phil67ago Consider adding your patch to the discussion at issue #3054.

**Closed by rear1019** 2020-04-27 15:04 UTC
Labels: Bug, CMake, swig
